---
exclude: ^roles
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.8.6
    hooks:
      - id: ansible-lint

  - repo: meta
    hooks:
      - id: check-hooks-apply
